# This is a commint CI
name: CI (PR)

on:
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare: 
    name: Check Out
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Detect package manager
        id: DPM
        run: DPMcm
      

  cache:
    needs: prepare
    name: Restore Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', 'app/components/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |  
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-  


  build-test:
    needs: cache
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: ${{ steps.DPM.outputs.manager }} ${{ steps.DPM.outputs.command }}

      - name: Build
        run: npm run build

