# copy from cloudflare
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: (env) pnpm
        run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node

      - run: pnpm install

      - run: make build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

  #   - name: Check - Broken Links
  #     run: pnpm run crawl
  #    if: success()

  #   - name: Check - Infinite redirects
  #     run: npx tsm bin/find-infinite-redirects.ts

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: (env) pnpm
  #       run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
  #     - run: pnpm install
  #     - run: pnpm run lint

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Setup Pages
        id: pages
        uses: actions/configure-page@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
