# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Setup ENV
        uses: actions/setup-node@v3
        with:
          node-version: 18.1
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: pnpm
        run: |
             curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
             pnpm install
    
      - name: Build
        env:
          # For maximum backward compatibility with Hugo modules
          NODE_OPTIONS: "--max-old-space-size=8192" 
        run: make build
  #         hugo \
  #         --gc \
  #         --minify \
  #         --baseURL "${{ steps.pages.outputs.base_url }}/"  
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
